---
title: "Module - CNV Analysis"
author: "BTC Pipeline"
date: "`r Sys.time()`"
output:
  html_document: 
    toc: true
    toc_float: true
    toc_depth: 4
    code_folding: show
    theme: united
    df_print: paged
params:
  project_name: 'Test'
  project_object: './dev/data/ovarian_cluster_object_determined_sanger.RDS'
  input_cnv_method: ["scven", "infercnv", "all"]
  n_threads: 8
  workdir: !r here::here()
  timestamp: !r Sys.Date()
  auto_save: !r TRUE
---

# Project Name: `r params$project_name`

```{r setup, include = FALSE, message = FALSE, warning = FALSE, echo = FALSE}

# Project parameters 
project_name <- params$project_name
project_object <- params$project_object

# Inputs and thresholds

# Optional parameters
opt_hgv_only <- params$opt_hgv_only

# Dataflow/Computational parameters
n_threads <- params$n_threads
n_memory <- params$n_memory

# Output parameters
work_directory <- params$workdir
timestamp <- params$timestamp
auto_save <- params$auto_save

# Rmarkdown options
knitr::opts_chunk$set(
  echo = TRUE,
  error = TRUE,
  message = FALSE, 
  warning = FALSE,
  fig.height = 8, 
  fig.width = 12,
  fig.align = 'center'
  )

knitr::opts_knit$set(
  root.dir = work_directory
  )

```

## Loading library

```{r library}

library(readr)
library(dplyr)
library(ggplot2)
library(Seurat)
library(SCEVAN)

```

## Folder structure

```{r project_directory}

if(!dir.exists(work_directory)) {
  dir.create(work_directory, recursive = T)
}

for(sub_directory in c('data')) {
  dir.create(paste0(work_directory, '/', sub_directory))
}

```

## Loading Seurat object

```{r loading_rds}

# Reading seurat object
seurat_object <- readRDS(file = project_object)

# Setting random seed
random_seed <- 2203
set.seed(random_seed)

```

```{r scevan}



```

## Saving DEG data.frame

```{r object_dump}

if(auto_save) {
  
  saveRDS(all_markers, file = paste0('data/', project_name, '_deg_analysis_', timestamp, '.RDS'))
  
}

```

------------------------------------------------------------------------

## Parameters log

```{r params_log, message = FALSE, warning = FALSE, echo = FALSE}

print(params)

```

## Session info

```{r session_info, message = FALSE, warning = FALSE, echo = FALSE}

sessionInfo()

```