---
title: "Module - Cell Stratification"
author: "BTC Pipeline"
date: "`r Sys.time()`"
output:
  html_document: 
    toc: TRUE
    toc_float: TRUE
    toc_depth: 4
    code_folding: show
    theme: united
    df_print: paged
    self_contained: TRUE
params:
  project_name: 'Test'
  project_object: './data/Test_main_cluster_object.RDS'
  input_cancer_type: 'Ovarian'
  input_stratification_method: 'infercnv_label'
  thr_proportion: 0.20
  thr_cluster_size: 1000
  thr_consensus_score: 2
  n_threads: 8
  n_memory: 16
  workdir: !r here::here()
  timestamp: !r Sys.Date()
  auto_save: TRUE
---

------------------------------------------------------------------------

# Project Name: `r params$project_name`

```{r setup, include = FALSE, message = FALSE, warning = FALSE, echo = FALSE}

# Project parameters 
project_name <- params$project_name
project_object <- params$project_object

# Inputs and thresholds
input_cancer_type <- params$input_cancer_type
input_stratification_method <- params$input_stratification_method

thr_proportion <- params$thr_proportion
thr_cluster_size <- params$thr_cluster_size
thr_consensus_score <- params$thr_consensus_score
# Optional parameters

# Dataflow/Computational parameters
n_threads <- params$n_threads
n_memory <- params$n_memory

# Output parameters
work_directory <- params$workdir
timestamp <- params$timestamp
auto_save <- params$auto_save

# Rmarkdown options
knitr::opts_chunk$set(
  echo = TRUE,
  error = TRUE,
  message = FALSE, 
  warning = FALSE,
  fig.height = 8, 
  fig.width = 12,
  fig.align = 'center',
  dpi = 300
  )

knitr::opts_knit$set(
  root.dir = work_directory
  )

```

## Loading library

```{r library}

library(readr)
library(dplyr)
library(ggplot2)
library(Seurat)
library(SCEVAN)
library(infercnv)
library(annotables)

```

## Folder structure

```{r project_directory}

if(!dir.exists(work_directory)) {
  dir.create(work_directory, recursive = T)
}

for(sub_directory in c('data', 'figures', 'figures/stratification')) {
  dir.create(paste0(work_directory, '/', sub_directory))
}

```

```{r loading_rds}

# Reading seurat object
seurat_object <- readRDS(file = project_object)

# Setting random seed
random_seed <- 2203
set.seed(random_seed)

```

## Clustering summary

```{r clustering_summary}

DimPlot(
    seurat_object, 
    reduction = "umap",
    label = TRUE,
    raster = FALSE,
    label.size = 12
  ) +
  theme(
    legend.position = 'top',
    legend.justification = 'center'
  )

```

## Cell markers score {.tabset}

```{r cell_markers_score}

# Major cell types markers
cell_lineage_markers <- list(
  "T-Cells" = c("CD3D","CD3E","CD4","CD8A","CD8B"), 
  "NK Cells" = c("NCAM1","KLRG1","FCGR3A","NKG7","GNLY","CD160"), 
  "B/Plasma Cells" = c("CD19","MS4A1","CD79A","CD79B","SDC1","MZB1","XBP1","JCHAIN"), 
  "Myeloid" = c("LYZ","S100A8","S100A9","CD68","CD14","C1QB","C1QC"), 
  "Endothelial Cells" = c("PECAM1","VWF","ENG","MCAM"), 
  "Fibroblast" = c("FAP","PDPN","COL1A2","DCN","COL3A1","COL6A1"),
  "Epithelial" = c("EPCAM","MUC1","ERBB2","KRT8","PGC","GKN2","SLC5A5","FABP1","KRT20")
)

# Cancer cell markers
malignant_markers <- list(
  "Ovarian" = c("WFDC2", "CD24", "CLDN3", "KRT7", "KRT17", "KRT18", "KRT19", "WT1", "CLDN4", "MSLN", "FOLR1", "MUC1"),
  "Glioblastoma" = c("EGFR", "KRT8", "KRT18", "KRT19") # Provisional
)

# Intersecting markers
intersecting_markers <- c(
  cell_lineage_markers, list(
  "Cancer" = malignant_markers[input_cancer_type]
))

# Calculating Module score
for(cell_type in names(intersecting_markers)) {
  seurat_object <- AddModuleScore(
  object = seurat_object,
  seed = random_seed,
  features = intersecting_markers[cell_type],
  name = cell_type
  )
}

# Removing group index on the module name
column_indexes <- sapply(names(intersecting_markers), function(column) {
      grep(column, colnames(seurat_object@meta.data))
})

colnames(seurat_object@meta.data)[column_indexes] <-
  gsub("1$", "", colnames(seurat_object@meta.data)[column_indexes])

```

## Cluster composition

```{r cluster_composition}

# Retrieving cluster composition
seurat_cluster_composition <- seurat_object@meta.data %>%
  mutate(
    total_cell_study = n()
  )

seurat_cluster_composition <- seurat_cluster_composition %>%
  group_by(seurat_clusters, patient_id, total_cell_study) %>%
  summarise(
    n_cell_per_patient = n()
  )

seurat_cluster_composition <- seurat_cluster_composition %>%
  group_by(patient_id) %>%
  mutate(
    total_cell_per_patient = sum(n_cell_per_patient)
  )

# Cell percentage per cluster
seurat_cluster_composition <- seurat_cluster_composition %>%
  group_by(seurat_clusters) %>%
  mutate(
    n_cell_per_cluster = sum(n_cell_per_patient),
    percentage = round((n_cell_per_patient / n_cell_per_cluster) * 100, 2)
  )

seurat_cluster_composition <- seurat_cluster_composition %>%
  select(seurat_clusters, patient_id, n_cell_per_patient,
         total_cell_per_patient, n_cell_per_cluster, total_cell_study, percentage)

# Hypergeometric test
seurat_cluster_composition <- seurat_cluster_composition %>%
  rowwise() %>%
  mutate(
    hyper_pvalue = phyper(
      q = n_cell_per_patient - 1,
      m = total_cell_study,
      n = total_cell_study - total_cell_per_patient,
      k = n_cell_per_cluster,
      lower.tail = FALSE
    )
  )

# Getting the lowest p-value
min_nonzero_p_value <- seurat_cluster_composition %>%
  pull(hyper_pvalue)

min_nonzero_p_value <- min(min_nonzero_p_value[min_nonzero_p_value > 0])

# Creating labels 
seurat_cluster_composition <- seurat_cluster_composition %>%
  rowwise() %>%
    mutate(
      hyper_p_log = -log10(
        ifelse(
          hyper_pvalue == 0, hyper_pvalue + min_nonzero_p_value, hyper_pvalue
        )
      ),
      hyper_p_label = ifelse(
        hyper_pvalue <= 0.05, "Yes", "No"
      )
  )

```

```{r enrichment_plot}

# Enrichment Plot
ggplot(seurat_cluster_composition, 
       aes(x = patient_id, y = seurat_clusters, color = hyper_p_label, size = hyper_p_log)) +
  geom_point() +
  labs(x = "Patient ID", y = "Seurat Clusters", color = "Is meaningful?", size = "-log10(P-value)") +
  theme_classic() +
  theme(
    legend.text = element_text(size = 14),
    legend.position = 'top',
    axis.text = element_text(size = 18)
  )

```

### Sample contributions (%)

```{r barplot_composition}

# Boxplot
ggplot(seurat_cluster_composition, aes(x = seurat_clusters, y = percentage, fill = patient_id)) +
  geom_col() +
  labs(x = "Seurat Clusters", y = "% of Cells", fill = "Patient ID:") +
  theme_classic() +
  theme(
    legend.text = element_text(size = 14),
    legend.position = 'top',
    axis.text = element_text(size = 18)
  )

```

### Patient-based UMAP

```{r umap_patient_plot}

umap_group <- DimPlot(seurat_object, reduction = "umap", group.by = "patient_id", raster = FALSE)
umap_group +
  theme(
    legend.position = 'bottom',
    legend.justification = 'center'
  )

```

```{r cluster_patient_specificty}

# Summarizing Hypergeometric
seurat_cluster_summarise <- seurat_cluster_composition %>%
  group_by(seurat_clusters) %>%
  summarise(
    enriched_by = sum(
      ifelse(
        hyper_pvalue <= 0.05, 1, 0
      )
    ),
    patient_specific = ifelse(
      enriched_by == 1, "Yes", "No"
    )
  )

seurat_cluster_summarise <- seurat_cluster_summarise %>%
  as.data.frame()

# Adding to Seurat annotation
seurat_object[['patient_enriched']] <- apply(seurat_object[["seurat_clusters"]], 1, function(cluster_id) {
  seurat_cluster_summarise[seurat_cluster_summarise$seurat_clusters == cluster_id, "patient_specific"]
})

```

```{r patient_specific_plot}

DimPlot(
    seurat_object, 
    group.by = 'patient_enriched',
    raster = FALSE,
    pt.size = 0.8
  ) +
  labs(colour = 'Patient-specific cluster:', title = NULL) +
  theme(
    legend.position = 'top',
    legend.justification = 'center'
  )

```


### Feature Plot

```{r cell_featureplot}

FeaturePlot(
  object = seurat_object, 
  features = names(intersecting_markers),
  min.cutoff = 'q1',
  raster = FALSE,
  )

```

### Violin Plot

```{r cell_violin}

VlnPlot(
  object = seurat_object,
  features = names(intersecting_markers)
  )

```
## Sampling cells

```{r sampling_per_clusters}

# Sampling cell per cluster
cluster_annotation <- seurat_object@meta.data %>%
  tibble::rownames_to_column(var = 'barcode') %>%
  select(barcode, orig.ident, seurat_clusters) %>%
  mutate(
    seurat_clusters = paste0('cluster_', seurat_clusters)
  )

# Categorizing cluster based on size
cluster_size <- table(cluster_annotation$seurat_clusters)
cluster_size_groups <- list(
  'large' = names(cluster_size[cluster_size >= thr_cluster_size]),
  'small' = names(cluster_size[cluster_size <= thr_cluster_size])
)

# Extracting cells per cluster category
large_cluster_members <- cluster_annotation %>%
  filter(seurat_clusters %in% cluster_size_groups$large) %>%
  group_by(seurat_clusters) %>%
  slice_sample(prop = thr_proportion)

small_cluster_members <- cluster_annotation %>%
  filter(seurat_clusters %in% cluster_size_groups$small)

# Formatting sampling vector
sample_cluster_members <- rbind(
  large_cluster_members,
  small_cluster_members
)

sample_cluster_list <- split(
  sample_cluster_members$barcode,
  sample_cluster_members$orig.ident
)

# Printing out
table(sample_cluster_members$seurat_clusters)
sum(table(sample_cluster_members$seurat_clusters))

```

## SCEVAN Analysis

```{r scevan_prepare}

scevan_sample_counts <- list()
for(sample_prefix in names(sample_cluster_list)) {
  
  sample_cols <- sample_cluster_list[[sample_prefix]]
  scevan_sample_counts[[sample_prefix]] <- seurat_object@assays$RNA@counts[, sample_cols] %>%
    as.matrix()
  
}

```

```{r scevan_run}

scven_result <- list()

for(sample_prefix in names(scevan_sample_counts)) {
  print(paste0(sample_prefix, "\n\n"))
  tryCatch(
    {
        scven_result[[sample_prefix]] <- pipelineCNA(
          scevan_sample_counts[[sample_prefix]],
          organism = 'human', 
          par_cores = n_threads, 
          SUBCLONES = FALSE)
    }, 
    
    error = function(e) 
    {
      print(paste0("-- Error on ", sample_prefix))
    }
  ) 
  
}

```

```{r scevan_output}

if(dir.exists('output')) {
  file.rename('output', 'data/scevan')  
}

```

```{r scevan_combine_metadata}

scven_annotation <- dplyr::bind_rows(scven_result)
seurat_object <- AddMetaData(
  seurat_object, 
  metadata = scven_annotation
  )

```

### SCEVAN UMAP

```{r scevan_visualization}

DimPlot(
    seurat_object, 
    group.by = 'class',
    raster = FALSE,
    pt.size = 0.8
  ) +
  labs(colour = 'SCEVAN annotation:', title = NULL) +
  theme(
    legend.position = 'top',
    legend.justification = 'center'
  )

```

## InferCNV Analysis

```{r infer_cnv_prepare}

infer_sample_list <- unlist(sample_cluster_list) %>%
  as.vector()

counts_matrix <- GetAssayData(seurat_object, slot = "counts")
counts_matrix <- counts_matrix[, infer_sample_list]

#
infercnv_annotation <- cluster_annotation %>%
  filter(barcode %in% infer_sample_list) %>% 
  select(barcode, seurat_clusters) %>%
  tibble::column_to_rownames(
    var = 'barcode'
  )

```

```{r infercnv_genes}

infercnv_genes <- annotables::grch38 %>%
  filter(biotype == "protein_coding") %>%
  arrange(chr, start) %>%
  distinct(symbol, chr, start, end) %>%
  mutate(
    chr = paste0('chr', chr)
  )

infercnv_genes <- infercnv_genes[!duplicated(infercnv_genes$symbol),]
infercnv_genes <- infercnv_genes %>%
  tibble::column_to_rownames(var = "symbol")

```

```{r infer_cnv_run}

infercnv_object <- infercnv::CreateInfercnvObject(
                            raw_counts_matrix = counts_matrix,
                            annotations_file = infercnv_annotation,
                            delim = "\t",
                            gene_order_file = infercnv_genes,
                            ref_group_names = NULL,
                            chr_exclude = c("chrX", "chrY", "chrM")
                            ) 

infercnv_object <- infercnv::run(infercnv_object,
                             cutoff = 0.1,
                             out_dir='./data/infercnv',
                             cluster_by_groups = TRUE,
                             analysis_mode = 'samples',
                             denoise = TRUE,
                             HMM = TRUE,
                             num_threads = n_threads
                             )

```

```{r infercnv_combine_meta}

# Loading infercnv object
seurat_infercnv_object <- seurat_object[,colnames(infercnv_object@expr.data)]
seurat_infercnv_object <- infercnv::add_to_seurat(
    infercnv_output_path = './data/infercnv',
    seurat_obj = seurat_infercnv_object,
    top_n = 10
  )

# Summarizing HMM score
infercnv_summarise_cnv <- seurat_infercnv_object@meta.data %>%
    rowwise() %>% 
    mutate(
      genomwide_cnv_proportion = sum(c_across(starts_with("proportion_scaled_cnv")), na.rm = TRUE),
      n_affected_chromosomes = sum(c_across(starts_with("has_cnv")), na.rm = TRUE)
    )

# 
genomwide_cnv_proportion <- infercnv_summarise_cnv$genomwide_cnv_proportion
n_affected_chromosomes <- infercnv_summarise_cnv$n_affected_chromosomes

# 
seurat_infercnv_object[['genomwide_cnv_proportion']] <- log1p(genomwide_cnv_proportion)
seurat_infercnv_object[['n_affected_chromosomes']] <- n_affected_chromosomes

```

### inferCNV UMAP

```{r infercnv_visualization}

FeaturePlot(seurat_infercnv_object, features = 'genomwide_cnv_proportion') +
  labs(title = "CNV - HMM score")

```

## Labeling malignant and normal cells {.tabset}

```{r infercnv_labeling_cells}

infercnv_cluster_cnv <- infercnv_summarise_cnv %>%
  group_by(seurat_clusters) %>%
  summarise(
    avg_genomwide_cnv_proportion = mean(genomwide_cnv_proportion)
  )

infercnv_cluster_cnv <- infercnv_cluster_cnv %>%
  mutate(
    infercnv_label = if_else(
      avg_genomwide_cnv_proportion >= mean(avg_genomwide_cnv_proportion), "Malignant", "nonMalignant"
    )
  )

# 
infercnv_label_matrix <- infercnv_cluster_cnv %>%
  select(seurat_clusters, infercnv_label) %>%
  tibble::column_to_rownames(var = "seurat_clusters")

#
seurat_object[['infercnv_label']] <- apply(seurat_object[["seurat_clusters"]], 1, function(cluster_id) {
  infercnv_label_matrix[cluster_id, "infercnv_label"]
})


```

```{r infercnv_annotation}

DimPlot(
    seurat_object, 
    reduction = "umap",
    label = TRUE,
    label.size = 12,
    raster = FALSE,
    group.by = "infercnv_label"
  ) +
  labs(title = "InferCNV Labels") +
  theme(
    legend.position = 'top',
    legend.justification = 'center'
  )

```

::: {.alert .alert-error}
Under-construction feature. Please, observed that results might be case-dependent.
:::

```{r cnv_consensus_score}

consensus_cnv_score <- seurat_infercnv_object@meta.data %>%
  select(seurat_clusters, genomwide_cnv_proportion, n_affected_chromosomes, class, Cancer, patient_enriched, Sort) %>%
  rename(scevan_label = class) %>%
  filter(scevan_label %in% c("tumor", "normal")) %>%
  mutate(
    scevan_to_numeric = case_match(
      scevan_label,
      "tumor"             ~ 2,
      "normal"            ~ 1
      ),
    patient_to_numeric = case_match(
      patient_enriched,
      "Yes"               ~ 2,
      "No"                ~ 1
    )
  )

#

consensus_cnv_score %>%
  arrange(seurat_clusters) %>%
  group_by(seurat_clusters) %>%
  top_n(10, Cancer)

```

```{r cnv_consensus_calcutation}

consensus_cnv_score <- consensus_cnv_score %>%
  mutate(
    consensus_score = (genomwide_cnv_proportion + Cancer) ^ patient_to_numeric
  )

#
con_mean <- mean(consensus_cnv_score$consensus_score, na.rm = TRUE)
con_stdv <- sd(consensus_cnv_score$consensus_score, na.rm = TRUE)

#
consensus_cnv_score$pvalue <- pnorm(
  consensus_cnv_score$consensus_score, mean = con_mean, sd = con_stdv, lower.tail = FALSE
  )

#
consensus_cluster_label <- consensus_cnv_score %>%
  group_by(seurat_clusters) %>%
  summarise(
    median_consensus_score = median(consensus_score),
    avg_pvalue = mean(pvalue)
  )

consensus_cluster_label <- consensus_cluster_label %>%
  mutate(
    consensus_label = if_else(
      median_consensus_score >= thr_consensus_score, "Malignant", "nonMalignant"
    )
  )

```

```{r consensus_visualizing}

consensus_cnv_score_plot <- merge(
  consensus_cnv_score,
  consensus_cluster_label,
  by = "seurat_clusters"
)

ggplot(consensus_cnv_score_plot, aes(x = seurat_clusters, y = consensus_score, fill = consensus_label)) +
  geom_boxplot() +
  labs(fill = "Predicted consensus label") +
  theme_classic() 

```

```{r consensus_combine_meta}

consensus_label_matrix <- consensus_cluster_label %>%
  select(seurat_clusters, consensus_label) %>%
  tibble::column_to_rownames(var = "seurat_clusters")

#

seurat_object[['consensus_label']] <- apply(seurat_object[["seurat_clusters"]], 1, function(cluster_id) {
  consensus_label_matrix[cluster_id, "consensus_label"]
})
 

```

```{r consensus_visualization}

umap_consensus <- DimPlot(
    seurat_object, 
    reduction = "umap",
    label = TRUE,
    label.size = 12,
    raster = FALSE,
    group.by = "consensus_label"
  ) +
  theme(
    legend.position = 'top',
    legend.justification = 'center'
  )

if(auto_save) {

  ggsave(plot = umap_consensus, filename = paste0('figures/stratification/UMAP_CONSENSUS_', timestamp, '.pdf'))

}

umap_consensus +
  labs(title = "Consensus score") +
  theme(
    legend.position = 'bottom'
  )

```

## Saving Seurat object

```{r object_dump}

# Saving full Seurat object
if(auto_save) {
  
  saveRDS(seurat_object, file = paste0('./data/', project_name, '_main_stratification_object.RDS'))
  
}

# Subsetting cells based on stratification analysis
for(cell_category in c("Malignant", "nonMalignant")) {
  
  subset_command_line <- parse(
    text = paste0("subset(seurat_object, subset = ", input_stratification_method,  " == \"", cell_category, "\")")
  )
  
  seurat_category_object <- eval(subset_command_line)

  if(auto_save) {
  
    saveRDS(seurat_category_object, file = paste0('./data/', project_name, "_", cell_category, '_stratification_object.RDS'))
  
  }

}

```

------------------------------------------------------------------------

## Parameters log

```{r params_log, message = FALSE, warning = FALSE, echo = FALSE}

print(params)

```

## Session info

```{r session_info, message = FALSE, warning = FALSE, echo = FALSE}

sessionInfo()

```
