---
title: "Module - Batch Correction"
author: "BTC Pipeline"
date: "`r Sys.time()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    code_folding: show
    self_contained: true
params:
  project_name: 'Test'
  project_object: './dev/data/Test_nonmalignant_annotation.RDS'
  input_target_variables: 'batch'
  input_batch_method: 'all'
  input_cell_stratification: 'infercnv_label'
  workdir: !r here::here()
  timestamp: !r Sys.Date()
  auto_save: !r TRUE
---

------------------------------------------------------------------------

# Project Name: `r params$project_name`

```{r setup, include = FALSE, message = FALSE, warning = FALSE, echo = FALSE}

# Project parameters 
project_name <- params$project_name
project_object <- params$project_object

# Filter and thresholds
input_batch_method <- params$input_batch_method
input_target_variables <- strsplit(
  params$input_target_variables, split = ';')[[1]]

# Optional parameters

# Dataflow/Computational parameters
input_cell_stratification <- params$input_cell_stratification

# Output parameters
work_directory <- params$workdir
timestamp <- params$timestamp
auto_save <- params$auto_save

# Rmarkdown options
knitr::opts_chunk$set(
  echo = TRUE,
  error = TRUE,
  message = FALSE, 
  warning = FALSE,
  fig.height = 8, 
  fig.width = 12,
  fig.align = 'center'
  )

knitr::opts_knit$set(
  root.dir = work_directory
  )

```

## Loading library

```{r library}

library(readr)
library(dplyr)
library(ggplot2)
library(Seurat)
library(SeuratWrappers)
library(harmony)
library(kBET)

```

## Folder structure

```{r project_directory}

if(!dir.exists(work_directory)) {
  dir.create(work_directory, recursive = T)
}

for(sub_directory in c('figures', 'figures/batch')) {
  dir.create(paste0(work_directory, '/', sub_directory))
}

```

```{r loading_rds}

# Reading seurat object
seurat_object <- readRDS(file = project_object)

# Setting random seed
random_seed <- 2203
set.seed(random_seed)

```

## Input validation

```{r basic_input_validation}

# Checking variables and metadata columns
meta_columns <- colnames(seurat_object@meta.data)

input_cell_stratification <- intersect(input_cell_stratification, meta_columns)
input_target_variables <- intersect(input_target_variables, meta_columns)

# Batch method
boolean_vector <- 
  switch(input_batch_method,
  'all' = c(T, T, T, T), 
  'cca' = c(T, F, F, F),
  'rpca' = c(F, T, F, F),
  'harmony' = c(F, F, T, F),
  'mnn' = c(F, F, F, T)
)

```

## Subseting Non-malignant cells

```{r seurat_subset_normal}

# Extracting normal cells based on stratification analysis
subset_command_line <- parse(
  text = paste0("subset(seurat_object, subset = ", input_cell_stratification,  " == \"Normal\")")
)

seurat_object <- eval(subset_command_line)

# Converting object to Seurat v5
options(Seurat.object.assay.version = "v5")
seurat_object[["RNA3"]] <- as(
  object = seurat_object[["RNA"]], Class = "Assay")
seurat_object[["RNA"]] <- as(
  object = seurat_object[["RNA"]], Class = "Assay5")

```

## Running batch correction methods

```{r cca_integration, eval = boolean_vector[[1]]}

seurat_object <- IntegrateLayers(
  object = seurat_object, 
  method = CCAIntegration,
  orig.reduction = "pca", 
  new.reduction = "integrated.cca",
  group.by = input_target_variables,
  verbose = FALSE
)

```

```{r rpca_integration, eval = boolean_vector[[2]]}

seurat_object <- IntegrateLayers(
  object = seurat_object, 
  method = RPCAIntegration,
  orig.reduction = "pca", 
  new.reduction = "integrated.rpca",
  group.by = input_target_variables,
  verbose = FALSE
)

```

```{r harmony_integration, eval = boolean_vector[[3]]}

seurat_object <- IntegrateLayers(
  object = seurat_object, 
  method = HarmonyIntegration,
  orig.reduction = "pca", 
  new.reduction = "intergrated.harmony",
  group.by = input_target_variables,
  verbose = FALSE
)

```

```{r fastmnn_integration, eval = boolean_vector[[4]]}

seurat_object <- IntegrateLayers(
  object = seurat_object, 
  method = FastMNNIntegration,
  new.reduction = "integrated.mnn",
  group.by = input_target_variables,
  verbose = FALSE
)

```

## Saving Seurat object

```{r object_dump}

if(auto_save) {
  
  saveRDS(seurat_object, file = paste0('./data/', project_name, '_batch_object.RDS'))
  
}

```

------------------------------------------------------------------------

## Parameters log

```{r params_log, message = FALSE, warning = FALSE, echo = FALSE}

print(params)

```

## Session info

```{r session_info, message = FALSE, warning = FALSE, echo = FALSE}

sessionInfo()

```
