---
title: "Module - CNV Analysis"
author: "BTC Pipeline"
date: "`r Sys.time()`"
output:
  html_document: 
    toc: TRUE
    toc_float: TRUE
    toc_depth: 4
    code_folding: show
    theme: united
    df_print: paged
    self_contained: TRUE
params:
  project_name: 'Test'
  project_object: './dev/data/ovarian_cluster_object_determined_sanger.RDS'
  input_cnv_method: 'all'
  input_analysis_mode: 'samples'
  input_organism: 'human'
  n_threads: 8
  workdir: !r here::here()
  timestamp: !r Sys.Date()
  auto_save: !r TRUE
---

# Project Name: `r params$project_name`

```{r setup, include = FALSE, message = FALSE, warning = FALSE, echo = FALSE}

# Project parameters 
project_name <- params$project_name
project_object <- params$project_object

# Inputs and thresholds
input_cnv_method <- params$input_cnv_method
input_organism <- params$input_organism

# Optional parameters

# Dataflow/Computational parameters
n_threads <- params$n_threads

# Output parameters
work_directory <- params$workdir
timestamp <- params$timestamp
auto_save <- params$auto_save

# Rmarkdown options
knitr::opts_chunk$set(
  echo = TRUE,
  error = TRUE,
  message = FALSE, 
  warning = FALSE,
  fig.height = 8, 
  fig.width = 12,
  fig.align = 'center',
  dpi = 300
  )

knitr::opts_knit$set(
  root.dir = work_directory
  )

```

## Loading library

```{r library}

library(readr)
library(dplyr)
library(ggplot2)
library(Seurat)
library(SCEVAN)

```

## Folder structure

```{r project_directory}

if(!dir.exists(work_directory)) {
  dir.create(work_directory, recursive = T)
}

for(sub_directory in c('data')) {
  dir.create(paste0(work_directory, '/', sub_directory))
}

```

## Loading Seurat object

```{r loading_rds}

# Reading seurat object
seurat_object <- readRDS(file = project_object)

# Setting random seed
random_seed <- 2203
set.seed(random_seed)

```

```{r basic_input_validation}

# CNV method
boolean_vector <- 
  switch(input_cnv_method,
  'all' = c(T, T), 
  'scevan' = c(T, F),
  'infercnv' = c(F, T)
  )

```

## SCEVAN Analysis

```{r splitting_matrices, eval = boolean_vector[[1]]}

# Extracting count matrices per sample
seurat_object_splitted <- SplitObject(seurat_object, split.by = "orig.ident")
seurat_object_splitted <- sapply(names(seurat_object_splitted), function(orig) {
      seurat_object_splitted[[orig]]@assays$RNA@counts 
  }
)

```

```{r running_scevan, eval = boolean_vector[[1]]}

# Running multisample SCEVAN - TO CHANGE
scevan_result <- multiSampleComparisonClonalCN(
  seurat_object_splitted,
  organism = input_organism,
  par_cores = n_threads
  )

```

```{r scevan_combine_metadata, eval = boolean_scevan}

scven_annotation <- dplyr::bind_rows(scevan_result[[1]])
seurat_object <- AddMetaData(
  seurat_object, 
  metadata = scven_annotation)

```

## InferCVN Analysis

```{r infercnv_reference, eval = boolean_vector[[2]]}

# Defining reference based on T-cell expression (TO-DO)
immune_cell_enrichment <- seurat_object@meta.data %>%
  select(seurat_clusters, `T-Cells1`)

#

ggplot(immune_cell_enrichment, aes(x = seurat_clusters, y = `T-Cells1`)) +
  geom_boxplot() +
  geom_signif() +
  theme_classic()

```

```{r running_infercnv, eval = boolean_vector[[2]]}

infercnv_object <- infercnv::CreateInfercnvObject(
                            raw_counts_matrix = counts_matrix,
                            annotations_file = infercnv_annotation,
                            delim = "\t",
                            gene_order_file = infercnv_genes_example, # To change
                            ref_group_names = NULL,
                            chr_exclude = c("chrX", "chrY", "chrM")) 

infercnv_object <- infercnv::run(infercnv_object,
                             cutoff = 0.1,
                             out_dir = 'infercnv', 
                             cluster_by_groups = TRUE,
                             analysis_mode = input_analysis_mode,
                             denoise = TRUE,
                             HMM = TRUE,
                             num_threads = n_threads
                             )

```

```{r infercnv_metadata, eval = boolean_vector[[2]]}

seurat_infercnv_object <- seurat_object[,colnames(infercnv_object@expr.data)]
seurat_infercnv_object <- infercnv::add_to_seurat(
  infercnv_output_path = './infercnv',
  seurat_obj = seurat_infercnv_object,
  top_n = 10
  )

#

infercnv_summarise_cnv <- seurat_infercnv_object@meta.data %>%
    rowwise() %>% 
    mutate(
      genomwide_cnv_proportion = sum(c_across(starts_with("proportion_scaled_cnv")), na.rm = TRUE),
      n_affected_chromosomes = sum(c_across(starts_with("has_cnv")), na.rm = TRUE)
      )

genomwide_cnv_proportion <- infercnv_summarise_cnv$genomwide_cnv_proportion
n_affected_chromosomes <- infercnv_summarise_cnv$n_affected_chromosomes

#

seurat_infercnv_object[['genomwide_cnv_proportion']] <- log1p(genomwide_cnv_proportion)
seurat_infercnv_object[['n_affected_chromosomes']] <- n_affected_chromosomes

```

## Saving DEG data.frame

```{r object_dump}

if(auto_save) {
  
  saveRDS(all_markers, file = paste0('data/', project_name, '_deg_analysis_', timestamp, '.RDS'))
  
}

```

------------------------------------------------------------------------

## Parameters log

```{r params_log, message = FALSE, warning = FALSE, echo = FALSE}

print(params)

```

## Session info

```{r session_info, message = FALSE, warning = FALSE, echo = FALSE}

sessionInfo()

```