---
title: "Module - Meta-program"
author: "BTC Pipeline"
date: "`r Sys.time()`"
output:
  html_document: 
    toc: TRUE
    toc_float: TRUE
    toc_depth: 4
    code_folding: show
    theme: united
    df_print: paged
    self_contained: TRUE
params:
  project_name: 'Test'
  project_object: './data/Test_Malignant_cluster_object.RDS'
  input_meta_programs: 'meta_programs_database.csv'
  input_cell_category: 'Malignant'
  input_heatmap_annotation: 'source_name;seurat_clusters'
  input_meta_step: 'main'
  n_threads: 8
  n_memory: 16
  workdir: !r here::here()  
  timestamp: !r Sys.Date()
  auto_save: !r TRUE
---

------------------------------------------------------------------------

# Project Name: `r params$project_name`

```{r setup, include = FALSE, message = FALSE, warning = FALSE, echo = FALSE}

# Project parameters 
project_name <- params$project_name
project_object <- params$project_object

# Inputs and thresholds
input_meta_programs <- params$input_meta_programs
input_cell_category <- params$input_cell_category
input_meta_step <- params$input_meta_step
input_heatmap_annotation <- strsplit(
  params$input_heatmap_annotation, split = ';')[[1]]

# Optional parameters

# Dataflow/Computational parameters
n_threads <- params$n_threads
n_memory <- params$n_memory

# Output parameters
work_directory <- params$workdir
timestamp <- params$timestamp
auto_save <- params$auto_save

# Rmarkdown options
knitr::opts_chunk$set(
  echo = TRUE,
  error = TRUE,
  cache = FALSE,
  message = FALSE, 
  warning = FALSE,
  fig.height = 8, 
  fig.width = 12,
  fig.align = 'center',
  dpi = 300
  )

knitr::opts_knit$set(
  root.dir = work_directory
  )

```

## Loading library

```{r library}

library(readr)
library(dplyr)
library(ggplot2)
library(scales)
library(Seurat)

```

## Folder structure

```{r project_directory}

if(!dir.exists(work_directory)) {
  dir.create(work_directory, recursive = T)
}

for(sub_directory in c('data', 'figures', 'figures/meta')) {
  dir.create(paste0(work_directory, '/', sub_directory))
}

# Cirro-related edition
file.create('figures/meta/.empty')

```

## Loading Seurat object

```{r loading_rds}

# Reading seurat object
seurat_object <- readRDS(file = project_object)

# Loading meta-programs
meta_programs_db <- read_csv(file = input_meta_programs)

# Setting random seed
random_seed <- 2203
set.seed(random_seed)

```

## Input validation

```{r basic_input_validation}

input_cell_category <- intersect(
  input_cell_category, c('B cells', 'CD4 T cells', 'CD8 T cells', 'Endothelial', 'Epithelial', 'Fibroblasts',
'Macrophages', 'Malignant')
)

meta_programs_db <- meta_programs_db %>%
  filter(source %in% input_cell_category)

```

## Clustering summary

```{r clustering_summary, fig.height = 12, fig.width = 14}

DimPlot(
    seurat_object, 
    reduction = "umap",
    label = TRUE,
    raster = FALSE,
    label.size = 12
  ) +
  theme(
    legend.position = 'top',
    legend.justification = 'center'
  )

```

## Module-score

```{r calculating_module_score}

# Converting to list
meta_programs <- split(
  meta_programs_db$gene_marker,
  meta_programs_db$meta_program
  )

# Fixing meta-programs names
names(meta_programs) <- 
  gsub("[()]", "", names(meta_programs))
names(meta_programs) <- 
  gsub(' ','_', names(meta_programs))

# Calculating ModuleScore
if(length(meta_programs) > 1) {
  
  for(program_type in names(meta_programs)) {
    seurat_object <- AddModuleScore(
      object = seurat_object,
      seed = random_seed,
      features = meta_programs[program_type],
      name = program_type
    )
  }
  
  # Removing seeds on Module name
  column_indexes <- sapply(names(meta_programs), function(column) {
        grep(paste0(column, "1"), colnames(seurat_object@meta.data))
  })
  
  colnames(seurat_object@meta.data)[column_indexes] <-
    gsub("1$", "", colnames(seurat_object@meta.data)[column_indexes])

}

```

## Plotting Meta-programs heatmap

```{r meta_heatmap, fig.height = 16, fig.width = 12}

# Preparing matrix and annotation
seurat_to_heatmap <- seurat_object@meta.data %>%
  tibble::rownames_to_column(var = "barcode")

# Extracting metadata and cluster labels
seurat_annotation_bar <- seurat_to_heatmap %>%
  tibble::column_to_rownames(var = "barcode") %>%
  select_at(input_heatmap_annotation)

# Retrieving module scores
seurat_meta_matrix <- seurat_to_heatmap %>%
  tibble::column_to_rownames(var = "barcode") %>%
  select(!!colnames(seurat_object@meta.data)[column_indexes])

seurat_meta_matrix <- seurat_meta_matrix %>%
  t()

seurat_meta_rescaled <- scales::rescale(
  seurat_meta_matrix, to = c(-2, 2))

# Meta-program heatmap
heat_plot <- pheatmap::pheatmap(
  seurat_meta_rescaled, 
  annotation_col = seurat_annotation_bar,
  clustering_distance_rows = 'correlation',
  clustering_distance_cols = 'correlation',
  clustering_method = 'ward.D',
  scale = 'row',
  color = colorRampPalette(c("blue", "white", "red"))(50),
  breaks = seq(-2, 2, length.out = 51),
  cluster_cols = TRUE,
  cutree_cols = 5,
  cutree_rows = 5,
  show_colnames = FALSE
  )

heat_plot

```

```{r saving_meta_heatmap}

# Saving in a PDF file
save_pheatmap <- 
  function(x, filename, width = 14, height = 10) {
   
  stopifnot(!missing(x))
  stopifnot(!missing(filename))
   
  pdf(filename, width = width, height = height)
   grid::grid.newpage()
   grid::grid.draw(x$gtable)
  dev.off()
}

save_pheatmap(heat_plot, paste0('figures/meta/', project_name, '_', input_meta_step,'_heatmap.pdf'))

```


### Feature Plot

```{r feature_plot, fig.height = 25}

FeaturePlot(
  object = seurat_object, 
  features = names(meta_programs),
  min.cutoff = 'q1')

```

## Saving Seurat object

```{r object_dump}

if(auto_save) {
  
  saveRDS(seurat_object, file = paste0('data/', project_name, '_', input_meta_step, '_meta_object.RDS'))
  write_tsv(meta_programs_db, file = paste0('data/meta_programs_db.tsv'))

}

```

------------------------------------------------------------------------

## Parameters log

```{r params_log, message = FALSE, warning = FALSE, echo = FALSE}

print(params)

```

## Session info

```{r session_info, message = FALSE, warning = FALSE, echo = FALSE}

sessionInfo()

```