---
title: "Module - Differential Expression"
author: "BTC Pipeline"
date: "`r Sys.time()`"
output:
  html_document: 
    toc: TRUE
    toc_float: TRUE
    toc_depth: 4
    code_folding: show
    theme: united
    df_print: paged
    self_contained: TRUE
params:
  project_name: 'Test'
  project_object: './data/Test_nonMalignant_cluster_object.RDS'
  input_deg_method: 'wilcox'
  input_integration_method: 'fastmnn'
  input_top_deg: 20
  input_step_name: "main"
  input_n_features: 2000
  thr_fold_change: 0.25
  thr_min_percentage: 0.1
  opt_hgv_filter: TRUE
  n_memory: 16
  n_threads: 8
  workdir: !r here::here()
  timestamp: !r Sys.Date()
  auto_save: TRUE
---

------------------------------------------------------------------------

# Project Name: `r params$project_name`

```{r setup, include = FALSE, message = FALSE, warning = FALSE, echo = FALSE}

# Project parameters 
project_name <- params$project_name
project_object <- params$project_object

# Inputs and thresholds
input_deg_method <- params$input_deg_method
input_top_deg <- params$input_top_deg
input_step_name <- params$input_step_name
input_integration_method <- params$input_integration_method
input_n_features <- params$input_n_features

thr_fold_change <- params$thr_fold_change
thr_min_percentage <- params$thr_min_percentage

# Optional parameters
opt_hgv_filter <- params$opt_hgv_filter

# Dataflow/Computational parameters
n_threads <- params$n_threads
n_memory <- params$n_memory

# Output parameters
work_directory <- params$workdir
timestamp <- params$timestamp
auto_save <- params$auto_save

# Rmarkdown options
knitr::opts_chunk$set(
  echo = TRUE,
  error = TRUE,
  cache = FALSE,
  message = FALSE, 
  warning = FALSE,
  fig.height = 8, 
  fig.width = 12,
  fig.align = 'center',
  dpi = 300
  )

knitr::opts_knit$set(
  root.dir = work_directory
  )

```

## Loading library

```{r library}

library(readr)
library(dplyr)
library(ggplot2)
library(Seurat)
library(future)
library(DT)

```

## Folder structure

```{r project_directory}

if(!dir.exists(work_directory)) {
  dir.create(work_directory, recursive = T)
}

for(sub_directory in c('data', 'figures/deg')) {
  dir.create(paste0(work_directory, '/', sub_directory))
}

```

## Loading Seurat object

```{r loading_rds}

# Reading seurat object
seurat_object <- readRDS(file = project_object)

# Setting random seed
random_seed <- 2203
set.seed(random_seed)

```

## Input validation

```{r basic_input_validation}

# Checking variables and metadata columns
meta_columns <- colnames(seurat_object@meta.data)
input_integration_method <- intersect(input_integration_method, meta_columns)

# Checking annotation
boolean_annotation <- FALSE
if("scytype" %in% meta_columns) {
  boolean_annotation <- TRUE
}
```

## Clustering summary {.tabset}

```{r clustering_summary, fig.height = 12, fig.width = 14}

DimPlot(
    seurat_object, 
    reduction = "umap",
    label = TRUE,
    raster = FALSE,
    label.size = 12
  ) +
  theme(
    legend.position = 'top',
    legend.justification = 'center'
  )

```

```{r cell_annot_summary, fig.height = 12, fig.width = 14, eval = boolean_annotation}

DimPlot(
    seurat_object, 
    reduction = "umap",
    group.by = "sctype",
    raster = FALSE,
  ) +
  theme(
    legend.position = 'top',
    legend.justification = 'center'
  )

```

```{r cell_annot_barplot, fig.height = 12, fig.width = 14, eval = boolean_annotation}



```

## Differential expression analysis

```{r finding_deg, message = FALSE, warning = FALSE, echo = TRUE, error = TRUE}

# Setting pland and memory limit
options(future.globals.maxSize = n_memory*1024^3)
plan("multicore", workers = n_threads)

# Sampling HGV
if(opt_hgv_filter) {
  
  # Retrieving VariableFeatures
  hvg <- FindVariableFeatures(
    object = seurat_object,
    selection.method = "vst",
     nfeatures = input_n_features
     )

  hvg <- VariableFeatures(object = seurat_object)
  
  # Finding DEG based on HGV genes
  all_markers <- FindAllMarkers(
    object = seurat_object,
    features = hvg,
    only.pos = FALSE,
    test.use = input_deg_method,
    logfc.threshold = thr_fold_change,
    random.seed = random_seed,
    min.pct = thr_min_percentage
    )

} else {
  
  # Finding all markers
  all_markers <- FindAllMarkers(
    object = seurat_object,
    only.pos = FALSE, 
    test.use = input_deg_method,
    logfc.threshold = thr_fold_change,
    random.seed = random_seed,
    min.pct = thr_min_percentage
    )

}

```

```{r deg_table, message = FALSE, warning = FALSE, echo = TRUE}

# Reordering all markers data.frame
all_markers <- all_markers %>%
  select(cluster, gene, pct.1, pct.2, p_val, avg_log2FC)

# Printing out all markers
datatable(all_markers, 
    class = 'cell-border stripe',
    rownames = FALSE,
    filter = 'top',
    width = '100%', 
    options = list(scrollX = TRUE)
    )

```

## Data Visualization {.tabset}

```{r extracting_top_deg}

# Extracting TOP20 DEGs per cluster
all_markers_per_cluster <- all_markers %>%
  group_by(cluster) %>%
  arrange(desc(avg_log2FC)) %>%
  mutate(
    rank = row_number()
  )

all_markers_per_cluster <- all_markers_per_cluster %>%
  group_by(cluster) %>%
  slice_max(n = input_top_deg, order_by = avg_log2FC)

# Removing redundant markers
all_markers_per_cluster <- all_markers_per_cluster[
  !duplicated(all_markers_per_cluster$gene),]

# Listing genes
top_degs_per_cluster <- all_markers_per_cluster %>%
  pull(gene)

```

```{r main_bubble_plot, fig.height = 12, fig.width = 45}

# Plotting DEGs
main_dotplot <- DotPlot(seurat_object, features = top_degs_per_cluster) +
  theme(
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 0.9),
    legend.position = 'top'
  )

main_dotplot

if(auto_save) {

  ggsave(plot = main_dotplot, filename = paste0('figures/deg/BUBBLEPLOT_', input_step_name, '.pdf'))

}

```

```{r annot_bubble_plot, fig.height = 45, fig.width = 12}

annot_dotplot <- DotPlot(seurat_object, features = top_degs_per_cluster, group.by = "sctype") +
  coord_flip() +
  theme(
    axis.text.y = element_text(size = 12),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 0.9),
    legend.position = 'top'
  )

annot_dotplot

if(auto_save) {

  ggsave(plot = annot_dotplot, filename = paste0('figures/deg/BUBBLEPLOT_ANNOTATION_', input_step_name, '.pdf'))

}

```

## Saving DEG data.frame

```{r object_dump}

if(auto_save) {
  
  saveRDS(all_markers, file = paste0('data/', project_name, "_", input_step_name, '_deg_table.RDS'))
  
}

```

------------------------------------------------------------------------

## Parameters log

```{r params_log, message = FALSE, warning = FALSE, echo = FALSE}

print(params)

```

## Session info

```{r session_info, message = FALSE, warning = FALSE, echo = FALSE}

sessionInfo()

```
