---
title: "Module - Cell communication"
author: "BTC scRNA Pipeline"
date: "`r Sys.time()`"
output:
  html_document:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 4
    code_folding: show
    self_contained: TRUE
    theme: united
    df_print: paged
params:
  project_name: 'Test'
  project_object: './data/Test_annotation_object.RDS'
  input_model_organism: 'human'
  input_source_groups: 'all'
  input_target_groups: 'all'
  input_cellchat_annotation: "Secreted Signaling"
  thr_top_connections: 20
  n_threads: 8
  n_memory: 8
  workdir: !r here::here()
  timestamp: !r Sys.Date()
  auto_save: TRUE
---

# Project Name: `r params$project_name`

```{r setup, include = FALSE, message = FALSE, warning = FALSE, echo = FALSE}

# Project parameters 
project_name <- params$project_name
project_object <- params$project_object

# Inputs and thresholds
input_source_groups <- strsplit(
  params$input_source_groups, split = ';')[[1]]
input_target_groups <- strsplit(
  params$input_target_groups, split = ';')[[1]]

input_cellchat_annotation <- params$input_cellchat_annotation

thr_top_connections <- params$thr_top_connections

# Dataflow/Computational parameters
n_threads <- params$n_threads
n_memory <- params$n_memory

# Output parameters
work_directory <- params$workdir
timestamp <- params$timestamp
auto_save <- params$auto_save

# Rmarkdown options
knitr::opts_chunk$set(
	echo = TRUE,
	error = TRUE,
	fig.align = "center",
	fig.height = 8,
	fig.width = 12,
	message = FALSE,
	warning = FALSE,
	dpi = 300
)
knitr::opts_knit$set(
  root.dir = work_directory
  )

```

## Loading library

```{r library}

library(readr)
library(dplyr)
library(ggplot2)
library(Seurat)
library(liana)
library(CellChat)
library(future)

# required to download expression data /w slow connection
options(timeout = 600)

```

## Folder structure

```{r project_directory}

if(!dir.exists(work_directory)) {
  dir.create(work_directory, recursive = T)
}

for(sub_directory in c('data', 'figures', 'figures/communication')) {
  dir.create(paste0(work_directory, '/', sub_directory))
}

# Cirro-related edition
file.create('figures/communication/.empty')

```

## Loading Seurat object

```{r loading_rds}

# Reading seurat object
seurat_object <- readRDS(file = project_object)

# Setting random seed
random_seed <- 2203
set.seed(random_seed)

```

## Input validation

```{r basic_input_validation}

if(input_source_groups == "all") {
  
  input_source_groups <- unique(seurat_object@meta.data$sctype)
  
}

if(input_target_groups == "all") {
  
  input_target_groups <- unique(seurat_object@meta.data$sctype)
  
}

```

## Clustering summary

```{r}

DimPlot(
    seurat_object, 
    reduction = 'umap',
    group.by = 'sctype',
    raster = FALSE,
    label = TRUE,
    label.size = 8
      ) +
    theme(
        legend.position = 'top',
        legend.justification = 'center'
    ) +
  labs(
      title = "scType"
  )

```

## LIANA Analysis

```{r}

liana_results <- liana_wrap(seurat_object, idents_col = "sctype") %>%
  liana_aggregate()

```

```{r}

liana_results

```

```{r}

liana_results %>%
  liana_dotplot(source_groups = input_source_groups,
                target_groups = input_target_groups,
                ntop = thr_top_connections) +
  theme(
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)
  )

```

```{r liana_heat}

liana_trunc <- liana_results %>%
  filter(aggregate_rank <= 0.01) 

heat_freq(liana_trunc)

```

```{r liana_chord}

chord_freq(liana_trunc)

```

##

```{r cellchat_convert}

cellchat <- createCellChat(object = seurat_object, group.by = "sctype")

```
```{r cellchat_database}

CellChatDB.use <- subsetDB(CellChatDB.human, search = input_cellchat_annotation) 
cellchat@DB <- CellChatDB.use

```

```{r cellchat_expressed}

future::plan("multisession", workers = n_threads)

cellchat <- subsetData(cellchat)
cellchat <- identifyOverExpressedGenes(cellchat)
cellchat <- identifyOverExpressedInteractions(cellchat)

```

```{r cellchat_probability}

cellchat <- computeCommunProb(cellchat)
cellchat <- filterCommunication(cellchat, min.cells = 10)

cellchat <- computeCommunProbPathway(cellchat)
cellchat <- aggregateNet(cellchat)

```

```{r cellchat_network}

groupSize <- as.numeric(table(cellchat@idents))

par(mfrow = c(1,2), xpd=TRUE)

netVisual_circle(cellchat@net$count, vertex.weight = groupSize, weight.scale = T, label.edge= F, title.name = "Number of interactions")
netVisual_circle(cellchat@net$weight, vertex.weight = groupSize, weight.scale = T, label.edge= F, title.name = "Interaction weights/strength")

```

```{r cellchat_zoom}

mat <- cellchat@net$weight
par(mfrow = c(3,4), xpd=TRUE)
for (i in 1:nrow(mat)) {
  mat2 <- matrix(0, nrow = nrow(mat), ncol = ncol(mat), dimnames = dimnames(mat))
  mat2[i, ] <- mat[i, ]
  netVisual_circle(mat2, vertex.weight = groupSize, weight.scale = T, edge.weight.max = max(mat), title.name = rownames(mat)[i])
}


```

## Saving Seurat object

```{r object_dump}

if(auto_save) {
  
  saveRDS(liana_results, file = paste0('data/', project_name, '_liana_object.RDS'))
  saveRDS(cellchat, file = paste0('data/', project_name, '_cellchat_object.RDS'))

}

```

## Parameters log

```{r params_log, message = FALSE, warning = FALSE, echo = FALSE}

print(params)

```

## Session info

```{r session_info, message = FALSE, warning = FALSE, echo = FALSE}

sessionInfo()

```