---
title: "Module - Batch Evaluation"
author: "BTC Pipeline"
date: "`r Sys.time()`"
output:
  html_document: 
    toc: true
    toc_float: true
    toc_depth: 4
    code_folding: show
    theme: united
    df_print: paged
params:
  project_name: 'Test'
  project_object: './data/Test_nonMalignant_batch_object.RDS'
  input_integration_evaluate: 'all'
  input_target_variables: 'batch'
  input_batch_step: 'nonMalignant'
  input_lisi_variables: 'cLISI;iLISI'
  input_auto_selection: TRUE
  thr_npc: 'auto' 
  thr_resolution: 0.25
  thr_cell_proportion: 0.30
  n_memory: 8
  n_threads: 8
  workdir: !r here::here()
  timestamp: !r Sys.Date()
  auto_save: TRUE
---

------------------------------------------------------------------------

# Project Name: `r params$project_name`

```{r setup, include = FALSE, message = FALSE, warning = FALSE, echo = FALSE}

# Project parameters 
project_name <- params$project_name
project_object <- params$project_object

# Inputs and thresholds
input_integration_evaluate <- params$input_integration_evaluate
input_target_variables <- params$input_target_variables
input_batch_step <- params$input_batch_step
input_auto_selection <- params$input_auto_selection
input_lisi_variables <- strsplit(
  params$input_lisi_variables, split = ';')[[1]]

thr_resolution <- params$thr_resolution
thr_npc <- params$thr_npc
thr_cell_proportion <- params$thr_cell_proportion

# Optional parameters

# Dataflow/Computational parameters
n_memory <- params$n_memory
n_threads <- params$n_threads

# Output parameters
work_directory <- params$workdir
timestamp <- params$timestamp
auto_save <- params$auto_save

# Rmarkdown options
knitr::opts_chunk$set(
  echo = TRUE,
  error = TRUE,
  message = FALSE, 
  warning = FALSE,
  fig.height = 8, 
  fig.width = 12,
  fig.align = 'center'
  )

knitr::opts_knit$set(
  root.dir = work_directory
  )

```

## Loading library

```{r library}

library(readr)
library(dplyr)
library(ggplot2)
library(Seurat)
library(kBET)
library(lisi)
library(patchwork)

if(!require('scPOP')) {
  devtools::install_github('vinay-swamy/scPOP')
}

library(scPOP)

```

## Folder structure

```{r project_directory}

if(!dir.exists(work_directory)) {
  dir.create(work_directory, recursive = T)
}

for(sub_directory in c('data', 'figures', 'figures/evaluation')) {
  dir.create(paste0(work_directory, '/', sub_directory))
}

```

## Loading Seurat object

```{r loading_rds}

# Reading seurat object
seurat_object <- readRDS(file = project_object)

# Cell number
ncell <- dim(seurat_object)[2]

# Knowledge-based parameters
if(thr_npc == 'auto') {
  thr_npc <- ifelse(ncell < 50000, 25, 50)
}

# Setting random seed
random_seed <- 2203
set.seed(random_seed)

# Setting pland and memory limit
options(future.globals.maxSize = n_memory*1024^3)

```

## Input validation

```{r basic_input_validation}

# Batch method
integration_method_vector <- 
  switch(input_integration_evaluate,
  'all' = c('integrated.cca', 'integrated.rpca', 'harmony', 'integrated.mnn'), 
  'cca' = 'cca',
  'rpca' = 'rpca',
  'harmony' = 'harmony',
  'mnn' = 'mnn'
)

integration_method_vector <- intersect(
  integration_method_vector,
  names(seurat_object@reductions)
)

```

## Sampling cells

```{r sampling_per_batch}

# Updating input_target_variables with sctype
input_target_variables <- c(
  input_target_variables,
  "sctype"
)

# Sampling cell per cluster
seurat_cell_subset <- seurat_object@meta.data %>%
  select_at(input_target_variables) %>%
  tibble::rownames_to_column(var = 'cell')
  
seurat_cell_subset <- seurat_cell_subset %>%
  group_by_at(input_target_variables) %>%
  sample_frac(size = thr_cell_proportion) %>%
  as.data.frame()

seurat_cell_subset <- seurat_cell_subset$cell

# Resizing Seurat object
seurat_object[["barcode"]] <- colnames(seurat_object)
seurat_object <- subset(
  seurat_object, subset = barcode %in% seurat_cell_subset)

# # of cells after filtering
table(seurat_object@meta.data[, input_target_variables])

```

## Quality metrics

```{r kbet_mean_calculation}

kbet_calcution <- function(seurat_object, batch_method) {
  
  kbet_list <- sapply(unique(seurat_object$seurat_clusters), function(cluster_id) {
    
    seurat_tmp <- subset(seurat_object, subset = seurat_clusters == cluster_id)
    data_tmp <- Embeddings(
      object = seurat_tmp, reduction = batch_method)
    batch_tmp <- seurat_tmp@meta.data$batch
    
    observed <- tryCatch(
      {
        kBET_tmp <- kBET(df = data_tmp, batch = batch_tmp, plot = FALSE)
        return(kBET_tmp$summary$kBET.observed[1])
      }, error = function(e) {
        return(0)
      }
    )
    
    observed
    
    }
  )

  mean_kBET <- sum(kbet_list)/length(unique(seurat_object$seurat_clusters))

}

```

```{r evaluation_quality_metrics}

quality_metrics_summarise <- list()

for (batch_method in integration_method_vector) {
  
  # Finding clusters
  seurat_object <- FindNeighbors(
    object = seurat_object, 
    reduction = batch_method, 
    dims = 1:thr_npc,
    graph.name = paste0('snn_npc', thr_npc)
  )

  # Setting multicore
  plan("multicore", workers = n_threads)
  
  seurat_object <- FindClusters(
    object = seurat_object,
    graph.name = paste0('snn_npc', thr_npc),
    cluster.name = paste0(batch_method, '_cluster'),
    resolution = thr_resolution
  )
  
  # Running UMAP reduction
  seurat_object <- RunUMAP(
    object = seurat_object,
    reduction.key = "umap_",
    reduction = batch_method, 
    dims = 1:thr_npc,
    reduction.name = paste0("umap_", batch_method),
    seed.use = random_seed
  )

  # Retrieving embeddings from batch method
  batch_method_embeddings <- Embeddings(
    object = seurat_object, reduction = batch_method
  )

  metrics <- run_all_metrics(
    reduction = batch_method_embeddings, 
    metadata = seurat_object@meta.data,
    batch_key = 'batch',
    label1_key = 'sctype',
    label2_key = 'seurat_clusters', 
    run_name = paste0(project_name, "_", batch_method)
  )
  
  metrics$kbet_mean <- kbet_calcution(seurat_object, batch_method)
  quality_metrics_summarise[[batch_method]] <- metrics
  
}

scpop_zscore <- scpop_zscore <- calc_sumZscore(
  lapply(names(quality_metrics_summarise), function(id_method) {
    quality_metrics_summarise[[id_method]][1:9]
  }),
  'batch'
  )

```

## Batch metrics inspection

```{r metrics_inspection}

quality_metrics_summarise <- do.call('rbind', quality_metrics_summarise)
quality_metrics_summarise$scpop_zscore <- scpop_zscore

quality_metrics_summarise

```

```{r ranking_best}

best_integration <- quality_metrics_summarise %>%
  filter(scpop_zscore == max(scpop_zscore)) %>%
  select(run) %>%
  pull()

best_integration <- sub(paste0(project_name, "_"), "", best_integration)

```

::: {.alert .alert-warning}
Under-construction: Accordingly with scPOP z-score the best integration method is **`r best_integration`**.
:::

## Data Visualization

### Integration summary

```{r integration_summary, fig.height = 12, fig.width = 14}

integration_umap <- list()

for(batch_method in integration_method_vector) {
  
  # Storing UMAP
  integration_umap[[batch_method]] <- DimPlot(
    seurat_object, 
    reduction = paste0("umap_", batch_method),
    group.by = 'batch',
    raster = FALSE,
  ) +
    labs(title = batch_method) +
  theme(
    legend.position = 'top',
    legend.justification = 'center'
  )
}

integration_umap$integrated.cca + integration_umap$integrated.rpca + integration_umap$harmony + integration_umap$integrated.mnn +
  plot_layout(ncol = 2)

```

### Clustering summary

```{r clustering_summary, fig.height = 12, fig.width = 14}

clustering_umap <- list()

for(batch_method in integration_method_vector) {
  
  # Storing UMAP
  clustering_umap[[batch_method]] <- DimPlot(
    seurat_object, 
    reduction = paste0("umap_", batch_method),
    group.by = paste0(batch_method, "_cluster"),
    raster = FALSE,
  ) +
    labs(title = batch_method) +
  theme(
    legend.position = 'top',
    legend.justification = 'center'
  )
}

clustering_umap$integrated.cca + clustering_umap$integrated.rpca + clustering_umap$harmony + clustering_umap$integrated.mnn +
  plot_layout(ncol = 2)

```

```{r lisi_calculation}

lisi_calculation <- function(
    seurat_object, input_integration_evaluate, batch_method) {
  
    data_tmp <- Embeddings(
        object = seurat_object, reduction = batch_method)
    
    seurat_object@meta.data <- seurat_object@meta.data %>%
      mutate(
        cluster_and_cell = paste0(sctype, "_-_", seurat_clusters)
      )
    
    lisi_result <- lisi::compute_lisi(
      data_tmp, 
      seurat_object@meta.data, 
      c('batch', 'sctype', 'seurat_clusters', 'cluster_and_cell', paste0(batch_method, '_cluster')),
      perplexity = 30
    )

    lisi_result <- lisi_result %>%
      tibble::rownames_to_column(var = "barcode") %>%
      tidyr::pivot_longer(
        !barcode, names_to = "lisi", values_to = "score") %>%
      mutate(
        lisi = case_when(
          lisi == "batch" ~ "iLISI",
          lisi == "sctype" ~ "cLISI",
          lisi == "seurat_clusters" ~ "ucLISI",
          lisi == "cluster_and_cell" ~ "ccLISI",
          lisi == paste0(batch_method, '_cluster') ~ "bcLISI"
        )
      )
    
    lisi_result <- merge(
      lisi_result,
      seurat_object@meta.data[
        , c("barcode", "seurat_clusters", "sctype", "cluster_and_cell", paste0(batch_method, '_cluster'))],
      by = "barcode"
    )
    
    lisi_result

}

```

### LISI scores

```{r lisi_harmoney_plot, fig.height = 30}

lisi_harmony_result <- lisi_calculation(
  seurat_object = seurat_object,
  input_integration_evaluate = input_integration_evaluate,
  batch_method = "harmony"
  )

# Subsetting display
lisi_harmony_subset <- lisi_harmony_result %>%
  filter(lisi %in% input_lisi_variables)

# Plotting LISI scores per cell
ggplot(lisi_harmony_subset, aes(x = score)) +
  geom_density() + 
  labs(title = "Harmony") +
  facet_wrap(sctype ~ lisi, scales = 'free', ncol = 2) +
  theme_classic() +
  theme(
    title = element_text(size = 20),
    axis.text = element_text(size = 12),
    strip.text = element_text(size = 16)
    )

```

```{r lisi_best_plot, fig.height = 30}

lisi_best_result <- lisi_calculation(
  seurat_object = seurat_object,
  input_integration_evaluate = input_integration_evaluate,
  batch_method = best_integration
  )

# Subsetting display
lisi_best_subset <- lisi_best_result %>%
  filter(lisi %in% input_lisi_variables)

# Plotting LISI scores per cell
ggplot(lisi_best_subset, aes(x = score)) +
  geom_density() + 
  labs(title = best_integration) +
  facet_wrap(sctype ~ lisi, scales = 'free', ncol = 2) +
  theme_classic() +
  theme(
    title = element_text(size = 20),
    axis.text = element_text(size = 12),
    strip.text = element_text(size = 16)
    )

```

## Saving BC evaluation data.frame

```{r object_dump}

if(input_auto_selection) {
  
  write_lines(best_integration, "./data/batch_method.selected.txt")
  
}

if(auto_save) {
  
  saveRDS(quality_metrics_summarise, file = paste0('data/', project_name, '_evaluation_table.RDS'))
  
}

```

------------------------------------------------------------------------

## Parameters log

```{r params_log, message = FALSE, warning = FALSE, echo = FALSE}

print(params)

```

## Session info

```{r session_info, message = FALSE, warning = FALSE, echo = FALSE}

sessionInfo()

```
